services:
  nginx:
    image: nginx
    networks:
      - devf
    tty: true
    labels:
       - "traefik.enable=true"
       - "traefik.http.routers.catchall.rule=HostRegexp(`{catchall:.*}`)"  # Catch-all rule for unmatched hosts
       - "traefik.http.routers.catchall.entrypoints=web"
       - "traefik.http.routers.catchall.priority=1"  # Set a low priority for catch-all
       - "traefik.http.services.catchall.loadbalancer.server.port=80"
    expose:
      - "80"
networks:
   devf:
     external: true
