services:
  nginx:
    image: devforge-nginx
    # image: nginx
    networks:
      - devf
    tty: true
    ports:
      - "80:80"
    volumes:
      - "../nginxData/sites-available:/etc/nginx/sites"
      - "../nginxData/staticContent:/etc/nginx/staticContent"
networks:
   devf:
     external: true
