

services:
  traefik:
    image: traefik
    ports:
      - "81:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - devf
    command: 
      - "--api.insecure=true"                         
      - "--providers.docker=true"                      
      - "--entrypoints.web.address=:80"                
networks:
  devf:
    external: true